"""Added Spreads table

Revision ID: 9175f1aeb939
Revises: 82ab27792ac8
Create Date: 2023-09-23 06:03:26.923216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9175f1aeb939'
down_revision = '82ab27792ac8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spread',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('odds_id', sa.String(length=50), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.Column('game_time', sa.DateTime(), nullable=False),
    sa.Column('home_team', sa.String(length=50), nullable=False),
    sa.Column('road_team', sa.String(length=50), nullable=False),
    sa.Column('home_team_spread', sa.Float(), nullable=False),
    sa.Column('road_team_spread', sa.Float(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('odds_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spread')
    # ### end Alembic commands ###
